---
title: "Spark setup"
subtitle: "Opsætning af Spark til brug i BagData 2, under wsl"

order: 3

date: 2026-09-1
date-modified: 2026-09-1

author: Søren Magnusson
author-meta: smag@tec.dk

# draft: true
---

## Playbook

### Start med at skifte til \~

``` bash
cd ~
```

check

```         
***:~$ cd ~
***:~$ pwd
/home/[user]
```

### Spark download

-   Åben en browser og søg på "spark download".
-   vælg den nyeste udgave af spark
-   vælg "Prebuilt with user-provided Apache Hadoop"
-   klick på linket "xxx.tgz", neden for
-   på linket "xxx.tgz" filen, højre klik og "kopier link adresse"

I konsollen, brug `wget`:

``` bash
wget https://dlcdn.apache.org/spark/spark-z.z.z/spark-z.z.z-bin-without-hadoop.tgz
```

Check sparkfilens størrelse og dato

```         
$ ls -l
total 1027928
drwxr-xr-x 4 smag smag      4096 Aug 31 17:25 BigData
-rw-r--r-- 1 smag smag 581280703 Apr  1 22:43 hadoop-3.5.0.tar.gz
-rw-r--r-- 1 smag smag 471301088 Jul 11 18:36 spark-4.2.0-bin-without-hadoop.tgz
```

### Udpak

``` bash
tar xvzf spark-z.z.z-bin-without-hadoop.tgz -C BigData/
```

check

``` bash
$ ls -l BigData/
total 8
drwxr-xr-x 13 smag smag 4096 Aug 31 16:39 hadoop-3.5.0
drwxr-xr-x 13 smag smag 4096 Jul 11 18:25 spark-4.2.0-bin-without-hadoop
```

### Rediger `.bashrc`

Tilføj nederst:

``` bash
# Spark
export SPARK_DIST_CLASSPATH=$(hadoop classpath)
export SPARK_HOME=/home/[user]/BigData/spark-z.z.z-bin-without-hadoop
export PATH=$SPARK_HOME/bin:$PATH
export PATH=$SPARK_HOME/sbin:$PATH
```

Husk at opdatere environment ved at køre `source ~/.bashrc`!

### Kopier `spark-env.sh`

I `~/BigData/spark-z.z.z-bin-without-hadoop/conf` skal `spark-env.sh.template` kopieres til `spark-env.sh`:

``` bash
cp BigData/spark-z.z.z-bin-without-hadoop/conf/spark-env.sh.template BigData/spark-z.z.z-bin-without-hadoop/conf/spark-env.sh
```

### Rediger `spark-env.sh`
Åben filen `~/BigData/spark-z.z.z-bin-without-hadoop/conf/spark-env.sh`
Tilføj nederst:
```bash
SPARK_MASTER_HOST=0.0.0.0
```


### Start Spark

``` bash
start-master.sh 
start-worker.sh spark://localhost:7077
```

Check ved at køre et job:

``` bash
spark-submit --master spark://localhost:7077 BigData/spark-z.z.z-bin-without-hadoop/examples/src/main/python/wordcount.py /user/smag/README.txt
```

::: callout-tip
## Hvis *wordcount* kører og viser en liste, så er du færdig!

Med mindre du vil lidt mere...
:::

Wordcount regnes for at være "hello world" i Big Data. Det tæller hyppigheden af de ord der i en tekstfil.

I mappen `spark-z.z.z-bin-without-hadoop/examples/src/main/python` kan man finde nogle eksempler.\


## Start og stop all

Spark har to medfølgende scripts, der starter og stopper spark master og worker mv; , `start-all.sh` og `stop-all.sh`.
De kører udenfor brugerens miljø, som vi har opsat i `.bashrc`. 

Derfor skal man duplikere de relevante linjer fra `.bashrc` over i bunden af `~/BigData/spark-z.z.z-bin-without-hadoop/conf/spark-env.sh`:

```bash
HADOOP_HOME=/home/[user]]/BigData/hadoop-x.x.x
HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin
HADOOP_OPTS="-Djava.library.path=$HADOOP_COMMON_LIB_NATIVE_DIR"

SPARK_DIST_CLASSPATH=$(hadoop classpath)
SPARK_HOME=/home/smag/BigData/spark-z.z.z-bin-without-hadoop
```
__Bemærk__: `[user]` og `x.x.x` skal erstattes med din bruger og hadoop-versionen, du har downloaded.  \
Desuden behøver der ikke stå `export` foran variablerne, da de _kun_ skal bruges i det script, der starter og stopper spark.

Desværre er der navnesammenfald mellem *hadoops* og *sparks* udgaver af `start-all.sh`og `stop-all.sh`. Så de skal kaldes med fuld sti, hvis man vil være sikker. \
Man sikkert lave et nyt script der starter og stopper både hadoop og spark...

Start og stop hadoop

``` bash
BigData/hadoop-x.x.x/sbin/start-all.sh
BigData/hadoop-x.x.x/sbin/stop-all.sh
```

Start og stop spark

``` bash
BigData/spark-z.z.z-bin-without-hadoop/sbin/start-all.sh
BigData/spark-z.z.z-bin-without-hadoop/sbin/stop-all.sh
```